/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/acknowledgements': RouteRecordInfo<'/acknowledgements', '/acknowledgements', Record<never, never>, Record<never, never>>,
    '/chat': RouteRecordInfo<'/chat', '/chat', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/app_usage': RouteRecordInfo<'/dashboard/app_usage', '/dashboard/app_usage', Record<never, never>, Record<never, never>>,
    '/dashboard/internet_usage': RouteRecordInfo<'/dashboard/internet_usage', '/dashboard/internet_usage', Record<never, never>, Record<never, never>>,
    '/dashboard/screenshots': RouteRecordInfo<'/dashboard/screenshots', '/dashboard/screenshots', Record<never, never>, Record<never, never>>,
    '/dashboard/TimeTables': RouteRecordInfo<'/dashboard/TimeTables', '/dashboard/TimeTables', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/proxy/categories': RouteRecordInfo<'/proxy/categories', '/proxy/categories', Record<never, never>, Record<never, never>>,
    '/proxy/phrases': RouteRecordInfo<'/proxy/phrases', '/proxy/phrases', Record<never, never>, Record<never, never>>,
    '/proxy/redirects': RouteRecordInfo<'/proxy/redirects', '/proxy/redirects', Record<never, never>, Record<never, never>>,
    '/proxy/times': RouteRecordInfo<'/proxy/times', '/proxy/times', Record<never, never>, Record<never, never>>,
    '/proxy/urls': RouteRecordInfo<'/proxy/urls', '/proxy/urls', Record<never, never>, Record<never, never>>,
    '/proxy/urls2': RouteRecordInfo<'/proxy/urls2', '/proxy/urls2', Record<never, never>, Record<never, never>>,
    '/Screenshots': RouteRecordInfo<'/Screenshots', '/Screenshots', Record<never, never>, Record<never, never>>,
    '/welcoming': RouteRecordInfo<'/welcoming', '/welcoming', Record<never, never>, Record<never, never>>,
  }
}
